### ISSUE TITLE
How can I change the highlight color to a lighter color?

### ISSUE THREAD

**Issue by bibek-maharjan** [shaggyfeng/obsidian-Golden-Topaz-theme#1]
![image](https://user-images.githubusercontent.com/76084262/120911731-50a9a580-c6a9-11eb-8499-f9312b4ae795.png)

**Comment by shaggyfeng** [comment]
Oh, dear. This highlight colour is ugly.  You should be able to get the new highlight colour if you just click `use` Golden Topaz in community theme now.
