### ISSUE TITLE
How to change the color of bolded words

### ISSUE THREAD

**Issue by jgsource** [shaggyfeng/obsidian-Golden-Topaz-theme#2]
I would like to change the color of bolded words to something more brighter. What code should I change to make the color to the same as the backlinks, a bright tannish color.

**Comment by shaggyfeng** [comment]
While using Obsidian, if you press CTRL-SHIFT-I (option-cmd-i for mac) then it will bring up the developer window. In the developer window, at the top left is an icon with a pointer in a box. This allows you to select elements on the screen and see how to refer to them and what styles. 
![image](https://user-images.githubusercontent.com/75353922/121234700-01f33b80-c862-11eb-94a8-696f992e8a46.png)

In your case, what you are looking for is this: 
` span.cm-strong, strong {
    color: var(--accent-strong);
}`

I changed it for you in the new update. Go to the community theme, and just click `use` Golden Topaz in community theme.

**Comment by shaggyfeng** [comment]
Fixed in v1.0.5

**Comment by shaggyfeng** [comment]
I only changed it for the light theme. if you want to change the dark theme one, the css code you are looking for is:  `--accent-strong`

**Comment by jgsource** [comment]
Really appreciate it mate! This is my favorite theme by far.
