### ISSUE TITLE
Support changing fonts

### ISSUE THREAD

**Issue by CavalloneChen** [shaggyfeng/obsidian-Golden-Topaz-theme#4]
Your theme is just gorgeous, thanks for your efforts.
One feature that is missing though is the ability to switch fonts. Perhaps you could consider integrating with the https://github.com/mgmeyers/obsidian-style-settings plugin?

**Comment by shaggyfeng** [comment]
I use the style plugin to change fonts. As you can see in the screenshots, I am using apple fonts on Windows. I will check if there is anything I can update as well.

**Comment by CavalloneChen** [comment]
> I use the style plugin to change fonts. As you can see in the screenshots, I am using apple fonts on Windows. I will check if there is anything I can update as well.

Which plugin specifically?

**Comment by shaggyfeng** [comment]
The only style plugin

**Comment by shaggyfeng** [comment]
> > I use the style plugin to change fonts. As you can see in the screenshots, I am using apple fonts on Windows. I will check if there is anything I can update as well.
> 
> Which plugin specifically?

Try to create a css file in the snippet folder in the .obsidian with the following code, and change the fonts to your liking.

/* @settings

name: Your Section Name Here
id: a-unique-id
settings:
    - 
        id: my-title
        title: My Settings
        type: heading
        level: 3
    - 
        id: accent
        title: Accent Color
        type: variable-color
        format: hsl-split
        default: '#007AFF'
    - 
        id: text
        title: UI font
        description: Font used for the user interface
        type: variable-text
        default: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen-Sans, Ubuntu, Cantarell, "Helvetica Neue", sans-serif

*/

**Comment by CavalloneChen** [comment]
> > > I use the style plugin to change fonts. As you can see in the screenshots, I am using apple fonts on Windows. I will check if there is anything I can update as well.
> > 
> > 
> > Which plugin specifically?
> 
> Try to create a css file in the snippet folder in the .obsidian with the following code, and change the fonts to your liking.
> 
> /* @settings
> 
> name: Your Section Name Here
> id: a-unique-id
> settings:
> -
> id: my-title
> title: My Settings
> type: heading
> level: 3
> -
> id: accent
> title: Accent Color
> type: variable-color
> format: hsl-split
> default: '#007AFF'
> -
> id: text
> title: UI font
> description: Font used for the user interface
> type: variable-text
> default: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen-Sans, Ubuntu, Cantarell, "Helvetica Neue", sans-serif
> 
> */

Thanks, but unfortunately this method does not work for me. Guess I'll have to wait for your future release.
