### ISSUE TITLE
How to change link colors

### ISSUE THREAD

**Issue by Jaris5** [shaggyfeng/obsidian-Golden-Topaz-theme#5]
I'm terribly new to Obsidian and I do love the colors of your theme. The background especially. But I find the accent color for links hard to differentiate (in Light mode). Is there a GUI way of modifying this and Header colors, etc.

I tried the Styles plugin, but it doesn't come up with any settings for this theme. (Excuse my ignorance!)
Thank you!

**Comment by shaggyfeng** [comment]
This should be helpful. https://forum.obsidian.md/t/getting-comfortable-with-obsidian-css/133
